services:
  _defaults:
    autowire: true

  LearnModernPhp\Chozetsu\:
    resource: '../src/Chozetsu/*'

  LearnModernPhp\Chozetsu\DependencyInjection\FizzBuzz\App\FizzBuzzSequencePrinter:
    public: true

  LearnModernPhp\Chozetsu\Solid\FizzBuzz\AbstractModel\Core\NumberConverter:
    arguments:
      $rules:
        - '@fizzbuzz.rule.fizz'
        - '@fizzbuzz.rule.buzz'
        - '@LearnModernPhp\Chozetsu\Solid\FizzBuzz\AbstractModel\Spec\PassThroughRule'

  fizzbuzz.rule.fizz:
    class: LearnModernPhp\Chozetsu\Solid\FizzBuzz\AbstractModel\Spec\CyclicNumberRule
    arguments: [ 3, 'Fizz' ]

  fizzbuzz.rule.buzz:
    class: LearnModernPhp\Chozetsu\Solid\FizzBuzz\AbstractModel\Spec\CyclicNumberRule
    arguments: [ 5, 'Buzz' ]

  LearnModernPhp\Chozetsu\DesignPatterns\AbstractFactory\Shop\PetShopInterface:
    class: LearnModernPhp\Chozetsu\DesignPatterns\AbstractFactory\Shop\CatAndDogOnlyPetShop
