name: Continuous Integration

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: none, mbstring, SimpleXML, dom, tokenizer, xml, xmlwriter
        coverage: xdebug

    - name: Install Composer Dependencies
      run: composer install

    - name: Format
      run: vendor/bin/php-cs-fixer fix --dry-run --diff
      env:
        PHP_CS_FIXER_IGNORE_ENV: 1

    - name: Cyclomatic complexity
      run: composer phpmd:ci

    - name: TypeChecking
      run: vendor/bin/phpstan analyse src tests

    - name: UnitTest
      run: vendor/bin/pest tests
