name: Format+TypeChecking+UnitTest

on:
  push:
    branches: [ main ]
    paths_ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths_ignore:
      - README.md
      - .gitignore

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: none, mbstring, SimpleXML
        coverage: xdebug
        tools: php-cs-fixer, phpunit

    - name: Install Composer Dependencies
      run: composer install

    - name: Format
      run: vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Cyclomatic complexity
      run: composer phpmd:ci

    - name: TypeChecking
      run: vendor/bin/phpstan analyse src tests

    - name: UnitTest
      run: vendor/bin/phpunit --display-warning --display-notice tests
